### list active runs
GET http://localhost:3000/api/process-worker/process-runs

### create a new run
POST http://localhost:3000/api/process-worker/process-runs
Content-Type: application/json

{
  "productVariantId": 1,
  "plannedQty": 150
}

### get run #3
GET http://localhost:3000/api/process-worker/process-runs/3

### start stepExecution #5
POST http://localhost:3000/api/process-worker/step-executions/5/start

### finish stepExecution #5
POST http://localhost:3000/api/process-worker/step-executions/5/finish

### finish run #3
POST http://localhost:3000/api/process-worker/finish/3